# Generated by Django 4.0.5 on 2022-08-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutadmin_announcementsadmin_cohortadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='index',
            name='news',
        ),
        migrations.RemoveField(
            model_name='index',
            name='socials',
        ),
        migrations.RemoveField(
            model_name='index',
            name='team',
        ),
    ]
