# Generated by Django 4.0.5 on 2022-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_index_contact_remove_index_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
