# Generated by Django 4.0.5 on 2022-08-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
