# Generated by Django 4.0.5 on 2022-08-15 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_staff_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='url_to_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
