# Generated by Django 4.0.5 on 2022-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_news_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date_published',
            field=models.DateTimeField(),
        ),
    ]
