# Generated by Django 4.0.5 on 2022-08-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_contact_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=64)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cohort')),
            ],
            options={
                'verbose_name_plural': 'Cohort Batches',
            },
        ),
    ]
