# Generated by Django 4.0.5 on 2022-08-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cohortbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='img',
            field=models.ImageField(upload_to='cohort'),
        ),
        migrations.CreateModel(
            name='CohortBatchAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=64)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cohort')),
            ],
        ),
    ]
