# Generated by Django 4.0.5 on 2022-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cohort_img_cohortbatchadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAdmin',
        ),
        migrations.DeleteModel(
            name='AnnouncementsAdmin',
        ),
        migrations.DeleteModel(
            name='CohortAdmin',
        ),
        migrations.RemoveField(
            model_name='cohortbatchadmin',
            name='cohort',
        ),
        migrations.DeleteModel(
            name='ContactAdmin',
        ),
        migrations.DeleteModel(
            name='EventAdmin',
        ),
        migrations.DeleteModel(
            name='NewsAdmin',
        ),
        migrations.DeleteModel(
            name='PublicationsAdmin',
        ),
        migrations.DeleteModel(
            name='RegisterAdmin',
        ),
        migrations.DeleteModel(
            name='SocialsAdmin',
        ),
        migrations.DeleteModel(
            name='StaffAdmin',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='img',
            field=models.ImageField(upload_to='cohort', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email1',
            field=models.CharField(max_length=32, verbose_name='first email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email2',
            field=models.CharField(max_length=32, verbose_name='second email'),
        ),
        migrations.AlterField(
            model_name='index',
            name='about_program_col1',
            field=models.TextField(verbose_name='About Section - Coloumn 1'),
        ),
        migrations.AlterField(
            model_name='index',
            name='about_program_col2',
            field=models.TextField(verbose_name='About Section - Coloumn 2'),
        ),
        migrations.AlterField(
            model_name='index',
            name='about_program_col3',
            field=models.TextField(verbose_name='About Section - Coloumn 3'),
        ),
        migrations.AlterField(
            model_name='index',
            name='about_program_col4',
            field=models.TextField(verbose_name='About Section - Coloumn 4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(upload_to='staff', verbose_name='Profile Picture'),
        ),
        migrations.DeleteModel(
            name='CohortBatchAdmin',
        ),
    ]
