# Generated by Django 4.0.5 on 2022-08-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_no',
        ),
    ]
